#!/usr/bin/env node
/**
 * Scans presets/ and generates src/presetsIndex.ts
 */

const fs = require("fs");
const path = require("path");

const PRESETS_DIR = path.join(__dirname, "..", "presets");
const OUTPUT_FILE = path.join(__dirname, "..", "src", "presetsIndex.ts");

const toConstName = (name) =>
  name
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();

const toVarName = (name) =>
  name
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

const presetDirs = fs.existsSync(PRESETS_DIR)
  ? fs
      .readdirSync(PRESETS_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort()
  : [];

const imports = [];
const exportsList = [];

presetDirs.forEach((dir) => {
  const dirPath = path.join(PRESETS_DIR, dir);
  const files = fs
    .readdirSync(dirPath)
    .filter((f) => f.endsWith(".json"))
    .sort();

  const constName = toConstName(dir);
  const presetNames = files.map((f) => path.basename(f, ".json"));

  presetNames.forEach((name) => {
    const varName = `${toVarName(dir)}_${toVarName(name)}`;
    const importPath = `../presets/${dir}/${name}.json`;
    imports.push(`import ${varName} from "${importPath}";`);
  });

  exportsList.push(
    `export const ${constName}_PRESET_NAMES = [\n  "none",\n${presetNames
      .map((p) => `  "${p}",`)
      .join("\n")}
] as const;`
  );

  exportsList.push(
    `export const ${constName}_PRESETS = {\n${presetNames
      .map((p) => {
        const varName = `${toVarName(dir)}_${toVarName(p)}`;
        return `  "${p}": ${varName},`;
      })
      .join("\n")}
} as const;`
  );
});

const content = `// Auto-generated by scripts/scan-presets.js
// Do not edit manually - run: npm run scan:presets

${imports.join("\n")}

${exportsList.join("\n\n")}
`;

fs.writeFileSync(OUTPUT_FILE, content);
console.log(`📝 Generated: src/presetsIndex.ts`);