#!/usr/bin/env node
/**
 * Scans the public/ folder for video files and backgrounds
 * Generates src/videoFiles.ts
 * Run: node scripts/scan-videos.js
 */

const fs = require('fs');
const path = require('path');

const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const BACKGROUNDS_DIR = path.join(PUBLIC_DIR, 'backgrounds');
const SCREENS_DIR = path.join(PUBLIC_DIR, 'screens');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'videoFiles.ts');

const VIDEO_EXTENSIONS = ['.mp4', '.mov', '.webm', '.m4v'];
const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
const AUDIO_EXTENSIONS = ['.mp3', '.wav'];
const ALL_MEDIA_EXTENSIONS = [...VIDEO_EXTENSIONS, ...IMAGE_EXTENSIONS];
const AUDIO_DIR = path.join(PUBLIC_DIR, 'audio');

function scanVideos() {
  const files = fs.readdirSync(PUBLIC_DIR);
  return files
    .filter(file => {
      const ext = path.extname(file).toLowerCase();
      // Only include video files (filter out directories by extension check)
      return VIDEO_EXTENSIONS.includes(ext);
    })
    .sort();
}

function scanBackgrounds() {
  // Create backgrounds folder if it doesn't exist
  if (!fs.existsSync(BACKGROUNDS_DIR)) {
    fs.mkdirSync(BACKGROUNDS_DIR, { recursive: true });
    return [];
  }

  const files = fs.readdirSync(BACKGROUNDS_DIR);
  return files
    .filter(file => {
      const ext = path.extname(file).toLowerCase();
      return ALL_MEDIA_EXTENSIONS.includes(ext);
    })
    .sort();
}

function scanAudio() {
  // Create audio folder if it doesn't exist
  if (!fs.existsSync(AUDIO_DIR)) {
    fs.mkdirSync(AUDIO_DIR, { recursive: true });
    return [];
  }

  const files = fs.readdirSync(AUDIO_DIR);
  return files
    .filter(file => {
      const ext = path.extname(file).toLowerCase();
      return AUDIO_EXTENSIONS.includes(ext);
    })
    .sort();
}

function scanScreens() {
  if (!fs.existsSync(SCREENS_DIR)) {
    fs.mkdirSync(SCREENS_DIR, { recursive: true });
    return [];
  }

  const files = fs.readdirSync(SCREENS_DIR);
  return files
    .filter(file => {
      const ext = path.extname(file).toLowerCase();
      return IMAGE_EXTENSIONS.includes(ext);
    })
    .map(file => `screens/${file}`)
    .sort();
}

function generateFile(videos, backgrounds, audio, screens) {
  const content = `// Auto-generated by scripts/scan-videos.js
// Do not edit manually - run: npm run scan:videos

export const VIDEO_FILES = [
${videos.map(v => `  "${v}",`).join('\n')}
] as const;

export type VideoFile = typeof VIDEO_FILES[number];

export const BACKGROUND_FILES = [
${backgrounds.length > 0 ? backgrounds.map(b => `  "${b}",`).join('\n') : '  // No background files found - add images/videos to public/backgrounds/'}
] as const;

export type BackgroundFile = typeof BACKGROUND_FILES[number];

export const AUDIO_FILES = [
${audio.length > 0 ? audio.map(a => `  "${a}",`).join('\n') : '  // No audio files found - add mp3/wav to public/audio/'}
] as const;

export type AudioFile = typeof AUDIO_FILES[number];

export const SCREEN_FILES = [
${screens.length > 0 ? screens.map(s => `  "${s}",`).join('\n') : '  // No screen files found - add images to public/screens/'}
] as const;

export type ScreenFile = typeof SCREEN_FILES[number];
`;

  fs.writeFileSync(OUTPUT_FILE, content);

  console.log(`✅ Found ${videos.length} demo video(s):`);
  videos.forEach(v => console.log(`   - ${v}`));

  console.log(`🖼️  Found ${backgrounds.length} background file(s):`);
  if (backgrounds.length > 0) {
    backgrounds.forEach(b => console.log(`   - backgrounds/${b}`));
  } else {
    console.log('   (none - add files to public/backgrounds/)');
  }

  console.log(`🎵 Found ${audio.length} audio file(s):`);
  if (audio.length > 0) {
    audio.forEach(a => console.log(`   - audio/${a}`));
  } else {
    console.log('   (none - add files to public/audio/)');
  }

  console.log(`📝 Generated: src/videoFiles.ts`);
}

const videos = scanVideos();
const backgrounds = scanBackgrounds();
const audio = scanAudio();
const screens = scanScreens();

if (videos.length === 0) {
  console.warn('⚠️  No video files found in public/. Using empty list.');
}

generateFile(videos, backgrounds, audio, screens);