// Auto-generated by scripts/scan-presets.js
// Do not edit manually - run: npm run scan:presets

import app_store_card_default from "../presets/app-store-card/default.json";
import app_store_card_last from "../presets/app-store-card/last.json";
import demo_video_default from "../presets/demo-video/default.json";
import demo_video_last from "../presets/demo-video/last.json";
import multi_scene_default from "../presets/multi-scene/default.json";
import three_phones_default from "../presets/three-phones/default.json";
import three_phones_last from "../presets/three-phones/last.json";

export const APP_STORE_CARD_PRESET_NAMES = [
  "none",
  "default",
  "last",
] as const;

export const APP_STORE_CARD_PRESETS = {
  "default": app_store_card_default,
  "last": app_store_card_last,
} as const;

export const DEMO_VIDEO_PRESET_NAMES = [
  "none",
  "default",
  "last",
] as const;

export const DEMO_VIDEO_PRESETS = {
  "default": demo_video_default,
  "last": demo_video_last,
} as const;

export const MULTI_SCENE_PRESET_NAMES = [
  "none",
  "default",
] as const;

export const MULTI_SCENE_PRESETS = {
  "default": multi_scene_default,
} as const;

export const THREE_PHONES_PRESET_NAMES = [
  "none",
  "default",
  "last",
] as const;

export const THREE_PHONES_PRESETS = {
  "default": three_phones_default,
  "last": three_phones_last,
} as const;
