// Auto-generated by scripts/scan-videos.js
// Do not edit manually - run: npm run scan:videos

export const VIDEO_FILES = [
  "habit_tracker.mov",
] as const;

export type VideoFile = typeof VIDEO_FILES[number];

export const BACKGROUND_FILES = [
  "grassy_field.jpg",
  "sunshine_field.jpg",
] as const;

export type BackgroundFile = typeof BACKGROUND_FILES[number];

export const AUDIO_FILES = [
  "sample-15s.mp3",
] as const;

export type AudioFile = typeof AUDIO_FILES[number];

export const SCREEN_FILES = [
  "screens/01_home_size.png",
  "screens/02_customize_tasks.png",
  "screens/03_room_select_exclude.png",
  "screens/app_logo_quest.png",
  "screens/app_logo_small.png",
  "screens/challenge.png",
  "screens/challenge2.png",
  "screens/challengedark.png",
  "screens/placeholder.png",
  "screens/settings.png",
  "screens/statistics.png",
] as const;

export type ScreenFile = typeof SCREEN_FILES[number];
